server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # La linea magica: si el archivo/directorio no existe, redirige el trafico a index.html
        try_files $uri $uri/ /index.html;
    }

    # Optimizacion: Cache a largo plazo para los estaticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}